### ISSUE TITLE
/Signal/config.json not found in directory /Signal

### ISSUE THREAD

**Issue by vinnytroia** [carderne/signal-export#56]
I am opening this as a new issue to my last comment. I have been able to tweak the OSX settings a bit and am getting closer. 

First: 

set SIGNAL_OUTPUT=~/Downloads/signal-output

set SIGNAL_INPUT=~/Library/Application Support/Signal

then I run: 

docker run --rm -it --name signal-export \
>   -v ${SIGNAL_INPUT}:/Signal \
>   -v ${SIGNAL_OUTPUT}:/output \
>   carderne/signal-export:latest

or: 

docker run --rm -it --name signal-export   -v ${SIGNAL_INPUT}:/Signal   -v ${SIGNAL_OUTPUT}:/output   carderne/signal-export:latest

**Output:** 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Error: /Signal/config.json not found in directory /Signal

I can clearly see config.json in my ~/Library/Application Support/Signal folder. 

Thanks

**Comment by carderne** [comment]
Hi @vinnytroia. The problem from your other issue https://github.com/carderne/signal-export/issues/52 and the config issue in this one is probably related to not quoting the paths. There seem to be some annoying inconsistencies in how Docker/bash/macOS/Linux deal with this. The culprit is that space in `Application Support`.

Try this:
```bash
docker run --rm -it --name signal-export \
  -v "~/Library/Application Support/Signal":/Signal \
  -v "~/Downloads/signal-output":/output \
  carderne/signal-export:latest
```

Or this:
```bash
docker run --rm -it --name signal-export \
  -v ~/Library/Application\ Support/Signal:/Signal \
  -v ~/Downloads/signal-output:/output \
  carderne/signal-export:latest
```

**Comment by carderne** [comment]
As for the `linux/arm64/v8` issue... I'll look into that, might need to build a separate Docker image for ARM users.

**Comment by Strengthless** [comment]
Same issue. 

Currently on Windows 10, using `Docker` and the `.bashrc` method.

```sh
signalexport () {
    if [[ -z "$1" ]]; then
        echo 'Must provide output path as first parameters'
        echo 'e.g. signalexport output'
    else
        input="$HOME/AppData/Roaming/Signal/"
        output="D:/My files/Downloads/Signal export/"
        shift 1
        winpty docker run --rm -it --name signal-export \
          -v "$input:/Signal" \
          -v "$output:/output" \
          carderne/signal-export:latest $@
    fi
}
```

The shell script has been modified, due to the following errors that occurred on my end.

1. `the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'`
Fixed this issue by adding `winpty` before the docker command, as suggested by [this stackoverflow article](https://stackoverflow.com/questions/48623005/docker-error-the-input-device-is-not-a-tty-if-you-are-using-mintty-try-prefi/49965690). 
2. `docker: invalid reference format: repository name must be lowercase.`
Fixed this issue by adding quotation marks to the `-v` argument, as suggested by this [stackoverflow article](https://stackoverflow.com/questions/48522615/docker-error-invalid-reference-format-repository-name-must-be-lowercase).

Now the two errors are gone, but I'm getting `Error: /Signal/config.json not found in directory /Signal` upon running `signalexport output --chats=Helix`. Any idea why?

**Comment by carderne** [comment]
Thanks @Strengthless for figuring that out, have made README and helper script a bit better.

As for the error you're still getting... 
1. Are you sure the Signal files _are_ in `"$HOME/AppData/Roaming/Signal/"`?
2. If they are, try running the image directly without the helper script:
```bash
winpty docker run --rm -it --name signal-export \
  -v "$HOME/AppData/Roaming/Signal/":/Signal \
  -v "D:/My files/Downloads/Signal export/":/output \
  carderne/signal-export:latest
```

**Comment by Strengthless** [comment]
Interesting... but nope, still doesn't work.

![image](https://user-images.githubusercontent.com/40143583/155760969-7aaec40c-e222-4900-8d02-bba3b8cd45cd.png)

![image](https://user-images.githubusercontent.com/40143583/155760775-3b3e3b7e-06f2-4f72-8844-9ae6ae9dfef9.png)

**Comment by carderne** [comment]
Maybe you need to play around with eg specifying the full path (with `C:/...` instead of `$HOME`) or something, but I can't help here. I don't even know what MINGW64 is.

**Comment by Strengthless** [comment]
As suggest by https://stackoverflow.com/a/53255978, I added an extra slash before the path, and it seemed to be working...?  

```sh
winpty docker run --rm -it --name signal-export \
          -v "/$input:/Signal" \
          -v "/$output:/output" \
          carderne/signal-export:latest $@
```

Not sure how/ why it worked though... But hey, at least it's a solution.

![image](https://user-images.githubusercontent.com/40143583/155763398-0ce4ba5a-1ece-46b1-9273-cbb0fcd1fe4a.png)

And then this I/O disk error occurred, and I managed to fix it by simply closing the Signal app. Apparently the database was being accessed and probably read-only, causing this error. 

Now the script is running and `Copying and renaming attachments`.  👍

**Comment by vinnytroia** [comment]
Update: 

When i try with quotes, i get this: 
docker: Error response from daemon: create ~/Library/Application Support/Signal: "~/Library/Application Support/Signal" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

when I try the other solution I get this: 
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 637, in main
    copy_attachments(src, dest, convos, contacts)
  File "/usr/local/lib/python3.9/site-packages/sigexport/main.py", line 70, in copy_attachments
    file_name += "." + att["contentType"].split("/")[1]
IndexError: list index out of range

**Comment by vinnytroia** [comment]
It turns out that your solution worked. 
docker run --rm -it --name signal-export \
  -v ~/Library/Application\ Support/Signal:/Signal \
  -v ~/Downloads/signal-output:/output \
  carderne/signal-export:latest

I realized that the index out of range just means I never specified which user to export!

**Comment by Qazzquimby** [comment]
In case it helps anyone, my issue was trying to work through WSL instead of powershell. In wsl the signal folder exists but is empty.

**Comment by seanwynwins** [comment]
I'm also getting this error. I tried running 

```
docker run --rm -it --name signal-export -v ~/Library/Application\ Support/Signal:/Signal -v ~/Downloads/signal-output:/output carderne/sigexport:latest
```

and I get the output
```
Using Docker to extract data, this may take a while the first time!
Error: using Docker method, but is Docker installed?
```

Seems like there's a [FileNotFound error](https://github.com/carderne/signal-export/blob/ca0e9a9e963e0b745a9e6bc219a89b930e27c63d/sigexport/main.py#L551) being thrown somehow, but both directories exist on my machine, not sure what's going on? I verified that Docker is installed and running (docker run hello-world works)

**Comment by seanwynwins** [comment]
Running

```
docker run carderne/sigexport --source ~/Library/Application\ Support/Signal/ --list-chats
```

I get the error 

```
Error: ~/Library/Application Support/Signal/config.json not found in directory ~/Library/Application Support/Signal
```

I checked that the config.json was there
